rss_feeds:
  - url: https://www.theverge.com/tech/rss/index.xml
    name: The Verge
  - url: https://www.wired.com/feed/rss
    name: Wired
  - url: https://techcrunch.com/feed/
    name: TechCrunch
  - url: https://mashable.com/feeds/rss/tech
    name: Mashable
  - url: https://feeds.arstechnica.com/arstechnica/technology-lab
    name: Ars Technica
  - url: https://www.techradar.com/feeds/tag/computing
    name: TechRadar
  - url: https://feeds.bloomberg.com/technology/news.rss
    name: Bloomberg
